### PR TITLE
Make PSGI_FILE test more readable

### PR DESCRIPTION
**Pull request by mnagy**
@ppisar PTAL. This is a cosmetic change, but I had real troubles reading and parsing the line in my head, I am hoping this is much simpler now. I found this while trying to hunt a test failure which I'll fix in an additional update to this PR, but I want to make it fail first so I can see the difference.

[test]

### CODE REVIEW

**Comment by mnagy** [comment]
Failed as expected. Pushed update fixing [test]s, they should now pass.

**Comment by ppisar** [comment]
This patch looks good.

**Comment by mnagy** [comment]
Turns out that I was using old source-to-image binary. The new one changed usage of --env so that it is used multiple times. However, there's apparently a bug in s2i that causes the environment variables not to be passed to the build container.

**Comment by mnagy** [comment]
@bparees cc about the bug. Caused by https://github.com/openshift/source-to-image/pull/501, I'm working on a fix.

**Comment by bparees** [comment]
thanks @mnagy

**Comment by mnagy** [comment]
[test]

**Comment by mnagy** [comment]
re[test]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
passed tests.  merging.

**Pull request merged**
